### ISSUE TITLE
Beacon frequency / contact threashold / epoch length

### ISSUE THREAD

**Issue by vaudenay** [DP-3T/reference_implementation#4]
Very nice code!

---

Epoch length is 15min.
Contact threshold is 2min.
(I assume the beacon frequency is 1-10Hz so very frequent compared to the above.)

If there is a contact during (4min -  2epsilon) starting at (end_of_epoch -  2min + epsilon), then this contact will not be registered because the EphID rotates and each EphID is met during less than 2min.

If we want to report for sure contacts longer than 2min, we should set the threshold to 1min.

The stored duration of an EphID contact is in seconds. It is between 2min and 15min. It may be underestimated by 2min.

**Comment by gannimo** [comment]
Thanks! We've internally talked about contacts that span across epochs and are planning to handle it similar to what you describe. The contact assessment in the code is an example. As we get the exact exposure and contact times from the epidemiologists, we'll change how contacts are calculated with the exact calculations!
