### ISSUE TITLE
Some tasks to do

### ISSUE THREAD

**Issue by ineiti** [DP-3T/reference_implementation#5]
Here a small list of things that would be nice:
- unit testing to make sure the edge-cases are correctly done (see #1)
- example data for people implementing libraries
- definition of the client/server API

**Comment by gannimo** [comment]
The goal of this repository is to serve as a simple example (in code) that show cases the different operations and aspects described in the technical whitepaper. It serves as an example for people that prefer code over prose.

While we do have unit tests and examples for different scenarios internally, we don't want to clutter this repository with lots of unnecessary code.

There will be separate documents for the client/server API when we release the SDK for the app/backends.

**Comment by ineiti** [comment]
I don't know where to ask questions, so I try here:

What language will the SDK be in?

Will the SDK also have test vectors? Something similar to http://ed25519.cr.yp.to/python/sign.input could be handy if somebody wants to create a library in another language. At least that's what saved me the last couple of times I had to implement an algorithm in another language.

**Comment by gannimo** [comment]
Please stay tuned until we release the SDK.
