### ISSUE TITLE
Typos in example_run (received beacons)

### ISSUE THREAD

**Issue by icascudo** [DP-3T/reference_implementation#6]
Hi,

I know this is just an example and will probably not be used in the future, but anyway I point out what I suppose are two typos in the code of example_run.py:

I think that in line 57 it should be _[alice_ephID]_ instead of _[bob_ephID]_

Likewise in lines 75,76,78,79 I suppose Bob and Isidor should only receive the ephimeral ID's of each other and not the whole list _beacons_, am I right? 
(As far as I understand the protocol, I guess Isidor does not get the beacon Alice sent to Bob before, even though Isidor is meeting Bob)

**Comment by gannimo** [comment]
The scenario in `eaxmple_run.py` is a shortened and simplified scenario from all the test cases we had and I made a mistake adjusting the IDs. Originally we had a bunch of extra situations in the example to illustrate different points but decided to optimice for simplicity. I pushed the fix. Thanks for pointing this out.
